### ISSUE TITLE
Always get 'swipe_error' even after successful activation and connection

### ISSUE THREAD

**Issue by smenchions** [elizabethrego/cordova-plugin-unimag-swiper#1]
Have been using your excellent cordova plugin but I am having trouble getting the card to swipe correctly.  I am always getting a 'swipe_error'.  I see in the java file, this indicates a JSON parse error?

Here are my details:

The problem occurs on Android with the Unimag II.  I haven't tried it on an apple device. Using Cordova 6.0.0

The plugin finds the unimag device and connects to it.  After connecting, I then call the swipe function to get ready for the swipe.  It works telling me in the logs, "Swipe Started".

When I swipe the credit card however, it always returns a "swipe_error" event.  Never a swipe_success.  I have tried multiple credit cards with no luck.  I have used the unimag utility app on the Google Play store and it allows me to swipe cards with it.  Any clues as to where I should start looking?
# 

```
self.initialize = function (callback) {
    //activate sdk and register notification callback

    if (!self.initialized()) {
        cordova.plugins.unimag.swiper.activate();
            cordova.plugins.unimag.swiper.enableLogs(true);
            cordova.plugins.unimag.swiper.setReaderType('unimag_ii');

            cordova.plugins.unimag.swiper.on('connected', function () {
                self.connected(true);
                self.swipe();
            });

            cordova.plugins.unimag.swiper.on('disconnected', function () {
                self.connected(false);
            });

            cordova.plugins.unimag.swiper.on('swipe_success', function (e) {
                var data = JSON.parse(e.detail);
                console.log('cardholder name: ' + data.first_name + ' ' + data.last_name);
                console.log('card number:' + data.card_number);
                console.log('expiration:' + data.expiry_month + '/' + data.expiry_year);
            });

            cordova.plugins.unimag.swiper.on('swipe_error', function () {
                console.log('ERROR: Could not parse card data.');
                self.swipe();
            });

            cordova.plugins.unimag.swiper.on('timeout', function (e) {
                if (self.connected()) {
                    console.log('ERROR: Swipe timed out - ' + e.detail);
                } else {
                    console.log('ERROR: Connection timed out - ' + e.detail);
                }
            });

            cordova.plugins.unimag.swiper.on('xml_error', function (e) {
                console.log('ERROR: Could not xml_error data.');
            });
    }




self.swipe = function () {
    if (self.connected()) {
        cordova.plugins.unimag.swiper.swipe(function successCallback() {
            console.log('SUCCESS: Swipe started.');
        }, function errorCallback() {
            console.log('ERROR: Could not start swipe.');
        });
    } else console.log('ERROR: Reader is not connected.');
};
```

**Comment by smenchions** [comment]
Closing this.  I figured it out after much testing and debugging.  I thought that there was a very very small possibility that the unimag card reader hardware itself was defective.  I shouldn't have dismissed that so easily.  By using xcode and setting breakpoints I found that the data returned from the card reader was really messed up in format. Tried a different card reader hardware and it worked.  

I might consider wiring up a return value for the swipe_error callback.  It would return the raw data from the magnetic card swipe if an error occurred.

**Comment by elizabethrego** [comment]
Hey! Sorry for such a delayed response on this - and thanks for getting to the root of the issue.

I agree that a value returned from the swipe_error callback would really help in this case.

**Comment by jocor87** [comment]
Hello,

I am getting always this same error. 

But I try with the [Demo Unimag App](https://play.google.com/store/apps/details?id=IDTech.MSR.uniMag.Demo&hl=en) and if it works in this demo app.

Also when I use autoconfig, it returns a successful message but then when I use swipe the device is disconnected.

I am using a Nexus 5.
